### ISSUE TITLE
Ask for datafiles

### ISSUE THREAD

**Issue by 1394125422** [pratapbhanu/RNTN#1]
Hello,I am so sorry to trouble you ,but I wonder if you could share the files of data.Now I am studying in the sentiment analysis ,so if you can share the data with me ,it will help me a lot in the studying.
Thanks for reading. If this troubles you,I will never do this .

**Comment by pratapbhanu** [comment]
Hi. If you are looking for sentiment analysis related data resources then you can download them from here: http://nlp.stanford.edu/sentiment/
It contains dataset along with their parse trees. I did for  Semantic Role Labeling on CoNLL-2003 dataset a couple of years ago.

**Comment by 1394125422** [comment]
OK,thanks for your replying,get it.

**Comment by pratapbhanu** [comment]
no problem.
